jgi-kbase/IDMappingService

README.md
design/design.md
src/jgikbase/idmapping/core/HashedToken.py
src/jgikbase/idmapping/core/Namespace.py
src/jgikbase/idmapping/core/NamespaceID.py
src/jgikbase/idmapping/core/NamespacedID.py
src/jgikbase/idmapping/core/User.py
src/jgikbase/idmapping/storage/Exceptions.py
src/jgikbase/idmapping/storage/IDMappingStorage.py
src/jgikbase/idmapping/storage/mongo/IDMappingMongoStorage.py

- removed metadata on mappings from design - could be 100B mappings. Use
descriptive namespace names instead (e.g. KBase Genome Objects, KBase
Assembly Objects)
-removed some pointless returns from the API

SCT-1147 Start on storage API, update design

---

Makefile
README.md
src/jgikbase/idmapping/storage/id_mapping_storage.py
src/jgikbase/idmapping/storage/mongo/id_mapping_mongo_storage.py
src/jgikbase/test/idmapping/mongo_controller.py
src/jgikbase/test/idmapping/storage/mongo/test_id_mapping_mongo_storage.py

Lots of TODOs here, but the basic test rig is working which deserves a PR.

SCT-1147 Add basic save/get user functions and mongo test rig

---

src/jgikbase/idmapping/storage/mongo/id_mapping_mongo_storage.py
src/jgikbase/test/idmapping/storage/mongo/test_id_mapping_mongo_storage.py

raw strings are nice
Also fix a test.

SCT-1147 simplify regex slightly, add docs.

---

src/jgikbase/idmapping/core/errors.py

instance var should be stripped as well

SCT-1147 More error message cleanup

---

src/jgikbase/idmapping/storage/id_mapping_storage.py
src/jgikbase/idmapping/storage/mongo/id_mapping_mongo_storage.py
src/jgikbase/test/idmapping/storage/mongo/test_id_mapping_mongo_storage.py

Need additional index for 'backwards' mapping searches.

SCT-147 Add getting a selection of namespaces, + add index

---

src/jgikbase/idmapping/core/errors.py
src/jgikbase/idmapping/core/mapper.py
src/jgikbase/idmapping/core/tokens.py
src/jgikbase/idmapping/core/user_handler.py
src/jgikbase/test/idmapping/core/mapper_test.py
src/jgikbase/test/idmapping/core/tokens_test.py

This is the glue code between the user handlers and storage system. The
API layer will call this code, whether via CLI or HTTP.

SCT-1233 Start on core mapping code implementation.

---

README.md
src/jgikbase/idmapping/core/object_id.py
src/jgikbase/idmapping/core/user.py
src/jgikbase/idmapping/core/user_handler.py
src/jgikbase/idmapping/storage/id_mapping_storage.py
src/jgikbase/idmapping/storage/mongo/id_mapping_mongo_storage.py
src/jgikbase/idmapping/userhandlers/kbase_user_handler.py
src/jgikbase/test/idmapping/core/object_id_test.py
src/jgikbase/test/idmapping/core/user_handler_test.py
src/jgikbase/test/idmapping/storage/mongo/test_id_mapping_mongo_storage.py

Also added \_\_SLOTS__ entries to classes where high class counts might occur.

SCT-1233 Mark users as admins in database

---

src/jgikbase/idmapping/core/mapper.py
src/jgikbase/idmapping/core/user_handler.py
src/jgikbase/idmapping/userhandlers/kbase_user_handler.py
src/jgikbase/test/idmapping/core/mapper_test.py
src/jgikbase/test/idmapping/core/user_handler_test.py
src/jgikbase/test/idmapping/userhandlers/kbase_user_handler_test.py

both cache times are returned so a) any calculations can occur in one place in
the code base, and b) so that the calculations use the same time source.

SCT-1221 Return cache times from user handlers

---

src/jgikbase/idmapping/core/mapper.py
src/jgikbase/test/idmapping/core/mapper_test.py

HandlerSet includes caching for all handlers

SCT-1221 Use HandlerSet instead of set(Handler) in mapper

---

src/jgikbase/idmapping/core/user_handler.py
src/jgikbase/idmapping/storage/id_mapping_storage.py
src/jgikbase/test/idmapping/core/user_handler_test.py

SCT-1221 Add set_user_as_admin to LocalUserHandler

---

id_mapper
src/jgikbase/idmapping/builder.py
src/jgikbase/idmapping/cli.py
src/jgikbase/test/idmapping/cli_test.py

list users done, still need
create
new token
admin
test config location

SCT-1243 CLI working

---

src/jgikbase/idmapping/cli.py
src/jgikbase/test/idmapping/cli_test.py

Also simplify input logic. The CLI will be very rarely used, so no need
for complex logic so multiple commands can occur with one invocation.

SCT-1243 Add create user fn to cli

---

src/jgikbase/idmapping/cli.py
src/jgikbase/test/idmapping/cli_test.py

Since the dbconn has a 30sec timeout

SCT-1243 Check inputs before trying to connect to db

---

src/jgikbase/idmapping/cli.py
src/jgikbase/test/idmapping/cli_test.py

SCT-1243 Add new token command to CLI.

---

src/jgikbase/idmapping/core/mapper.py
src/jgikbase/idmapping/storage/mongo/id_mapping_mongo_storage.py
src/jgikbase/test/idmapping/storage/mongo/test_id_mapping_mongo_storage.py

Not sure why mypy didn't catch this. Should've AFAICT.

Fix data storage system bug

---

design/design.md
mypy.ini
requirements.txt
src/jgikbase/idmapping/core/errors.py
src/jgikbase/idmapping/core/mapper.py
src/jgikbase/idmapping/core/user.py
src/jgikbase/idmapping/service/mapper_service.py
src/jgikbase/test/idmapping/service/mapper_service_test.py

Only gets namespaces for now.
Tested with a full stack manually, will add integration tests later.

SCT-1251 Add a working server.

---

src/jgikbase/idmapping/builder.py
src/jgikbase/idmapping/cli.py
src/jgikbase/idmapping/config.py
src/jgikbase/idmapping/core/user.py
src/jgikbase/test/idmapping/builder_test.py
src/jgikbase/test/idmapping/cli_test.py
src/jgikbase/test/idmapping/user_lookup_test_module.py

Tested manually with the cli script and the service.
This doesn't test the user name verification yet, but will test later.

SCT-1221 Add user lookup configuration to the builder.

---

src/jgikbase/idmapping/core/user.py
src/jgikbase/idmapping/userlookup/jgi_user_lookup_prototype.py
src/jgikbase/test/idmapping/core/user_test.py

See notes in file as to why it's a prototype.

SCT-1221 Add prototype JGI user lookup handler.

---

src/jgikbase/idmapping/service/mapper_service.py
src/jgikbase/test/idmapping/service/mapper_service_test.py

Ids in body to allow for / ? & etc
Bulk lookup
Currently the bulk implementation is only at the API level. Push it down
the stack as needed for performance purposes.

SCT-1251 Update get_mappings for new design

---

src/jgikbase/idmapping/service/mapper_service.py
src/jgikbase/test/idmapping/service/mapper_service_test.py

Currently the bulk implementation is only at the API level. Push it down
the stack as needed for performance purposes.

SCT-1251 Make create & remove mappings bulk update

---

Dockerfile
deployment/conf/.templates/settings.py.templ

Update Docker build

---

README.md
src/jgikbase/idmapping/builder.py
src/jgikbase/idmapping/core/user.py
src/jgikbase/idmapping/service/mapper_service.py
src/jgikbase/idmapping/storage/id_mapping_storage.py
src/jgikbase/idmapping/storage/mongo/id_mapping_mongo_storage.py
src/jgikbase/test/idmapping/service/mapper_service_test.py
src/jgikbase/test/idmapping/storage/mongo/test_id_mapping_mongo_storage.py

Reverts jgi-kbase/IDMappingService#104

Revert "SCT-1147 Fix get namespaces bug"

---

Dockerfile
deployment/conf/.templates/deployment.cfg.templ
docker-compose.yml

Need to put a token in the env (for auth_source_kbase_init_token) for adding users to namespaces to work.

docker-compose up works

---

Makefile
src/jgikbase/idmapping/builder.py
src/jgikbase/idmapping/cli.py
src/jgikbase/idmapping/config.py
src/jgikbase/idmapping/core/arg_check.py
src/jgikbase/idmapping/core/errors.py
src/jgikbase/idmapping/core/mapper.py
src/jgikbase/idmapping/core/object_id.py
src/jgikbase/idmapping/core/user_lookup.py
src/jgikbase/idmapping/service/mapper_service.py
src/jgikbase/idmapping/storage/id_mapping_storage.py
src/jgikbase/idmapping/storage/mongo/id_mapping_mongo_storage.py
src/jgikbase/idmapping/userlookup/kbase_user_lookup.py
src/jgikbase/test/idmapping/core/tokens_test.py
src/jgikbase/test/idmapping/core/user_lookup_test.py
src/jgikbase/test/idmapping/core/user_test.py
src/jgikbase/test/idmapping/integration/service_test.py
src/jgikbase/test/idmapping/mongo_controller.py
src/jgikbase/test/idmapping/service/mapper_service_test.py
src/jgikbase/test/idmapping/storage/mongo/test_id_mapping_mongo_storage.py
src/jgikbase/test/idmapping/test_utils.py

Will fix flake8, mypy, bandit in 3 different PRs.

Fix flake8
